# Generated by Django 3.1.8 on 2022-09-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visa',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='visaThumbnails'),
        ),
        migrations.AlterField(
            model_name='visa',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='visa',
            name='documents_required',
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='visacategory',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
