# Generated by Django 3.2 on 2022-12-11 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('package', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayBooking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=255)),
                ('payment_id', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.holidaypackage')),
                ('selected_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.pricecategory')),
                ('selected_duration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.duration')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('room_no', models.CharField(default='', max_length=255)),
                ('holidayBooking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='booking.holidaybooking')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('dob', models.DateTimeField()),
                ('passport_no', models.CharField(max_length=255)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='booking.room')),
            ],
        ),
    ]
